### ISSUE TITLE
Dependency on MPI

### ISSUE THREAD

**Issue by ddeboni** [pwrapi/pwrapi-ref#5]
The distributed collection runtime has a dependency on MPI.  We need to have a configuration flag for where MPI is located and allow for compilation without MPI (--without-mpi) similar to how we are conditionally compiling Python.

**Comment by cmcantalupo** [comment]
It is bundled with a few other changes in this commit, but below is the solution we use in geopm for optionally configuring with MPI support:

https://github.com/geopm/geopm/commit/6c52e6f98dd7ed11f7ebbbe66d5b5d10ed4d646e

Let me know if you have any comments or suggestions.

**Comment by ddeboni** [comment]
Thanks for the info.  We are in the process of staging changes to reflect v1.2 of the specification and should have this updated in the next day or so.

**Comment by ddeboni** [comment]
Added MPI build with and without
